### PR TITLE
add jitter warning to readme

### PR DESCRIPTION
**Pull request by Hyphen-ated**
I spent a few hours the other day trying to set up input display over fxpak USB and I learned that it inherently has a ton of jitter with the current firmware, so it's no good for my use case. I would like to save others the trouble of learning this the hard way

### CODE REVIEW

**Comment by Skarsnik** [comment]
I am not sure to understand what you call Jiter. delay?

**Comment by Hyphen-ated** [comment]
Jitter means an unpredictable amount of delay.
If you press a button and measure how long it takes the button to show up on the input display, it might show up after a delay of 1, 2, 3, 4, or 5 frames. basically a random chance every time.
It's caused here because every 250ms the fxpak firmware saves snes SRAM to the sd card. It takes about 80ms for it to perform the save, and during that 80ms it won't talk over USB. so the input display won't update during those frames.

**Comment by Skarsnik** [comment]
Ok, maybe you can reword it as "The usb2snes support may not be suited for you if you need 100% accuracy, consider using a hardware based approach (note that Button Mash support these)"

**Comment by Hyphen-ated** [comment]
"not 100%" is a little vague, like if it were 99.9% that would be fine for a lot of people, but it's more like 70% accurate

how about this:

`Note: if you're using a USB connection to an FxPak/Sd2Snes, the firmware will stop communicating for a period of about 5 frames, multiple times per second. This means the input display will not update during those times. If you need 100% accuracy, consider a hardware based input display solution (which Button Mash also supports) `

**Comment by Skarsnik** [comment]
Good :)

**Pull request merged**
